baseurl = "https://tuenguyen004.github.io/"
publishDir = "docs"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 10

[params]
  contentTypeName = "projects"
  themeColor = "orange"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true
  singlePageSite = true


[languages]
    [languages.en]
        title = "Tue's Portfolio"
        subtitle = ""
        keywords = ""
        copyright = ""
        menuMore = "show more"
        readMore = "read more"
        readOtherPosts = "read other posts"

        [languages.en.params.logo]
        logoText = "Tue's Portfolio / An Engineering Student"
        logoSplit = " / "   # Places logo text blocks in to spans so they wrap nicely
        logoHomeLink = "/"

        [languages.en.menu]
        [[languages.en.menu.main]]
            identifier = "welcome"
            name = "about me"
            url = "/#welcome"
            weight = 1
        [[languages.en.menu.main]]
            identifier = "projects"
            name = "things i've done"
            url = "/projects"
            weight = 2
        [[languages.en.menu.main]]
            identifier = "contact"
            name = "resume + contact"
            url = "/#contact"
            weight = 3
        [[languages.en.menu.main]]
            identifier = "about"
            name = "who's 2A?"
            url = "/#about"
            weight = 4
